[versions]
activity = "1.9.0"
androidGradlePlugin = "8.5.0"
apollo = "3.8.3"
coil = "2.6.0"
compose = "2024.06.00"
core = "1.13.1"
espresso = "3.5.1"
firebase = "33.1.0"
firebaseCrashlyticsGradle = "3.0.1"
googleServices = "4.4.2"
gson = "2.11.0"
hilt = "2.51.1"
hiltNavigation = "1.2.0"
junit = "4.13.2"
junitAndroid = "1.1.5"
kotlin = "1.9.24"
kotlinCoroutines = "1.8.1"
kotlinSerialization = "1.6.3"
ksp = "1.9.24-1.0.20"
lifecycle = "2.8.2"
navigation = "2.7.7"
okhttp = "4.12.0"
paging = "3.3.0"
review = "2.0.1"
retrofit = "2.11.0"
room = "2.6.1"
splash = "1.0.1"
truth = "1.4.2"

[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
android-library = { id = "com.android.library", version.ref = "androidGradlePlugin" }
apollo = { id = "com.apollographql.apollo3", version.ref = "apollo" }
firebase-crashlytics-gradle = { id = "com.google.firebase.crashlytics", version.ref = "firebaseCrashlyticsGradle" }
google-services = { id = "com.google.gms.google-services", version.ref = "googleServices" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }

[libraries]
activity = { module = "androidx.activity:activity-compose", version.ref = "activity" }
apollo = { module = "com.apollographql.apollo3:apollo-runtime", version.ref = "apollo" }
coil = { module = "io.coil-kt:coil-compose", version.ref = "coil" }
compose-bom = { module = "androidx.compose:compose-bom", version.ref = "compose" }
compose-foundation = { module = "androidx.compose.foundation:foundation" }
compose-material = { module = "androidx.compose.material:material" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
core = { module = "androidx.core:core-ktx", version.ref = "core" }
espresso = { module = "androidx.test.espresso:espresso-core", version.ref = "espresso" }
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebase" }
firebase-analytics = { module = "com.google.firebase:firebase-analytics" }
firebase-crashlytics = { module = "com.google.firebase:firebase-crashlytics" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hilt-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hilt" }
hilt-navigation = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hiltNavigation" }
junit-test = { module = "junit:junit", version.ref = "junit" }
junit-test-android = { module = "androidx.test.ext:junit", version.ref = "junitAndroid" }
kotlin-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinCoroutines" }
kotlin-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinSerialization" }
lifecycle-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle" }
lifecycle-compose = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "lifecycle" }
navigation = { module = "androidx.navigation:navigation-compose", version.ref = "navigation" }
okhttp-bom = { module = "com.squareup.okhttp3:okhttp-bom", version.ref = "okhttp" }
okhttp = { module = "com.squareup.okhttp3:okhttp" }
okhttp-logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor" }
paging-compose = { module = "androidx.paging:paging-compose", version.ref = "paging" }
paging-runtime = { module = "androidx.paging:paging-runtime", version.ref = "paging" }
paging-common = { module = "androidx.paging:paging-common", version.ref = "paging" }
review-ktx = { module = "com.google.android.play:review-ktx", version.ref = "review" }
review = { module = "com.google.android.play:review", version.ref = "review" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
retrofit-gson-converter = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
room-paging = { module = "androidx.room:room-paging", version.ref = "room" }
splash = { module = "androidx.core:core-splashscreen", version.ref = "splash" }
truth = { module = "com.google.truth:truth", version.ref = "truth" }

[bundles]
compose = ["compose-material", "compose-foundation", "compose-ui-tooling", "compose-ui-tooling-preview"]
lifecycle = ["lifecycle-ktx", "lifecycle-compose"]
okhttp = ["okhttp", "okhttp-logging-interceptor"]
paging = ["paging-compose", "paging-runtime"]
retrofit = ["retrofit", "gson", "retrofit-gson-converter"]
review = ["review", "review-ktx"]
