[versions]
sdk-min = "24"
sdk-compile = "35"
sdk-target = "35"

app-namespace = "com.montfel.pokfinder"
app-version-code = "15"
app-version-name = "1.2.5"

activity = "1.10.0"
agp = "8.7.3"
apollo = "3.8.5"
coil = "2.7.0"
compose = "2025.01.01"
core = "1.15.0"
dependencyAnalysis = "2.8.0"
detekt = "1.23.6"
firebase = "33.9.0"
firebaseCrashlyticsGradle = "3.0.3"
googleServices = "4.4.2"
gson = "2.11.0"
hilt = "2.53.1"
hiltNavigation = "1.2.0"
kotlin = "2.1.0"
kotlinCoroutines = "1.10.1"
kotlinSerialization = "1.8.0"
ksp = "2.1.0-1.0.29"
lifecycle = "2.8.7"
navigation = "2.8.6"
okhttp = "4.12.0"
paging = "3.3.5"
retrofit = "2.11.0"
review = "2.0.2"
room = "2.6.1"
splash = "1.0.1"

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
apollo = { id = "com.apollographql.apollo3", version.ref = "apollo" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
dependency-analysis = { id = "com.autonomousapps.dependency-analysis", version.ref = "dependencyAnalysis" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
firebase-crashlytics-gradle = { id = "com.google.firebase.crashlytics", version.ref = "firebaseCrashlyticsGradle" }
google-services = { id = "com.google.gms.google-services", version.ref = "googleServices" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }

# Convention Plugins
pokfinder-android-application = { id = "pokfinder.android.application", version = "unspecified" }
pokfinder-android-library = { id = "pokfinder.android.library", version = "unspecified" }
pokfinder-compose-library = { id = "pokfinder.compose.library", version = "unspecified" }
pokfinder-kotlin-library = { id = "pokfinder.kotlin.library", version = "unspecified" }

[libraries]
activity = { module = "androidx.activity:activity-compose", version.ref = "activity" }
apollo = { module = "com.apollographql.apollo3:apollo-runtime", version.ref = "apollo" }
coil = { module = "io.coil-kt:coil-compose", version.ref = "coil" }
compose-bom = { module = "androidx.compose:compose-bom", version.ref = "compose" }
compose-foundation = { module = "androidx.compose.foundation:foundation" }
compose-material3 = { module = "androidx.compose.material3:material3" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
core = { module = "androidx.core:core-ktx", version.ref = "core" }
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebase" }
firebase-analytics = { module = "com.google.firebase:firebase-analytics" }
firebase-crashlytics = { module = "com.google.firebase:firebase-crashlytics" }
gradle-plugin-android = { group = "com.android.tools.build", name = "gradle", version.ref = "agp" }
gradle-plugin-detekt = { group = "io.gitlab.arturbosch.detekt", name = "detekt-gradle-plugin", version.ref = "detekt" }
gradle-plugin-kotlin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hilt-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hilt" }
hilt-core = { module = "com.google.dagger:hilt-core", version.ref = "hilt" }
hilt-navigation = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hiltNavigation" }
kotlin-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinCoroutines" }
kotlin-serialization-core = { module = "org.jetbrains.kotlinx:kotlinx-serialization-core", version.ref = "kotlinSerialization" }
kotlin-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinSerialization" }
lifecycle-compose = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "lifecycle" }
navigation = { module = "androidx.navigation:navigation-compose", version.ref = "navigation" }
okhttp-bom = { module = "com.squareup.okhttp3:okhttp-bom", version.ref = "okhttp" }
okhttp = { module = "com.squareup.okhttp3:okhttp" }
okhttp-logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor" }
paging-common = { module = "androidx.paging:paging-common", version.ref = "paging" }
paging-compose = { module = "androidx.paging:paging-compose", version.ref = "paging" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
retrofit-gson-converter = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit" }
review = { module = "com.google.android.play:review", version.ref = "review" }
review-ktx = { module = "com.google.android.play:review-ktx", version.ref = "review" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
room-paging = { module = "androidx.room:room-paging", version.ref = "room" }
room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
splash = { module = "androidx.core:core-splashscreen", version.ref = "splash" }

[bundles]
compose = ["compose-material3", "compose-foundation", "compose-ui-tooling", "compose-ui-tooling-preview"]
okhttp = ["okhttp", "okhttp-logging-interceptor"]
review = ["review", "review-ktx"]
